source 'git@github.com:SuperAwesomeLTD/pj-Private-CocoaPods.git'
source 'git@github.com:SuperAwesomeLTD/sa-private-pods-specs-ios.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
use_frameworks!
#use_frameworks! :linkage => :static # Use this when Admob enabled
#use_modular_headers!

target 'SuperAwesomeExample' do
  pod 'SuperAwesome', :path => '../'
#  pod 'SuperAwesome/Main', :path => '../'
#  pod 'SuperAwesome/Core', :path => '../', :testspecs => ['Tests']
#  pod 'SuperAwesome/Moya', :path => '../', :testspecs => ['Tests']
#  pod 'SuperAwesome/MoPub', :path => '../'
#  pod 'SuperAwesome/Unity', :path => '../'
#  pod 'SuperAwesome/AIR', :path => '../'
#  pod 'SAAgeGate'

  target 'Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
    pod 'Nimble'
    pod 'Mockingjay'
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.2'
          end
      end
  end
end
