platform :ios, '10.0'
use_frameworks!
use_modular_headers!

target 'SuperAwesomeExample' do
  pod 'SuperAwesome/Full', :path => '../'
#  pod 'SuperAwesome/MoPub', :path => '../'
#  pod 'SuperAwesome/Unity', :path => '../'
#  pod 'SuperAwesome/AIR', :path => '../'
125gx#  pod 'SuperAwesome/AdMob', :path => '..§      §q`§1rd4/'
#  pod 'SAAgeGate'

  target 'Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
    pod 'Nimble'
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.2'
          end
      end
  end
end
