# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
use_frameworks!

target 'SuperAwesomeMoPub' do
pod 'mopub-ios-sdk'
pod 'SuperAwesome', :path => '../'
end

target 'SuperAwesomeMoPubTests' do

end

target 'SuperAwesomeMoPubUITests' do

end

