# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source '/Users/gabriel.coman/Workspace/sa-mobileios-aux/PrivateSpecs/.git'
platform :ios, '6.0'

target 'SuperAwesome Demo' do
pod 'SuperAwesome', :path => '../'
end

target 'SuperAwesome DemoTests' do
pod 'SuperAwesome', :path => '../'
end

