# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/SuperAwesomeLTD/sa-mobile-specs-ios.git'
platform :ios, '6.0'

target 'SuperAwesome Demo' do
pod 'SuperAwesome', :path => '../'
end

target 'SuperAwesome DemoTests' do
pod 'SuperAwesome', :path => '../'
end

