# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperAwesomeIronSourceExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuperAwesomeIronSourceExample
  pod 'IronSourceSDK'
  pod 'IronSourceSuperAwesomeAdapter','4.1.7.0'
end
